insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (1, 'Sponge Cake Mix - Chocolate', 4865, '', 4924, 2);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (2, 'Pepper - White, Whole', 9913, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 3706, 71);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (3, 'Cookies Oatmeal Raisin', 18505, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1337, 37);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (4, 'Vodka - Hot, Lnferno', 16556, '', 3866, 16);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (5, 'Mop Head - Cotton, 24 Oz', 5649, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 2653, 18);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (6, 'Ice Cream - Life Savers', 8108, '', 882, 97);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (7, 'Wine - Fume Blanc Fetzer', 3471, '', 794, 100);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (8, 'Cheese - Taleggio D.o.p.', 2345, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1888, 58);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (9, 'Chevril', 9051, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 889, 36);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (10, 'Wine - White, Chardonnay', 2695, '', 4708, 94);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (11, 'Creme De Cacao Mcguines', 18877, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 2576, 31);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (12, 'Pate - Peppercorn', 17712, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 2679, 38);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (13, 'Tomatoes - Heirloom', 19554, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1256, 82);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (14, 'Buffalo - Short Rib Fresh', 1158, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 4661, 69);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (15, 'Jagermeister', 5080, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 3893, 99);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (16, 'Lamb - Ground', 11102, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 2719, 16);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (17, 'Beef - Shank', 16026, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 3227, 74);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (18, 'Blueberries - Frozen', 8298, '', 2640, 64);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (19, 'Shrimp - Tiger 21/25', 8134, '', 1210, 82);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (20, 'Foam Espresso Cup Plain White', 10082, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 4993, 21);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (21, 'V8 Pet', 16061, '', 3870, 99);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (22, 'Wine - Pinot Noir Pond Haddock', 15626, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1417, 73);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (23, 'Coconut Milk - Unsweetened', 4196, '', 4532, 66);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (24, 'Cheese - Parmesan Grated', 16323, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 2832, 80);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (25, 'Muffin - Mix - Bran And Maple 15l', 7384, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 3719, 27);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (26, 'Lettuce - Spring Mix', 10450, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 2231, 89);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (27, 'Blueberries', 16016, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1597, 7);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (28, 'Turnip - White, Organic', 11220, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 4412, 10);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (29, 'Coffee Cup 16oz Foam', 18893, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1564, 62);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (30, 'Potatoes - Yukon Gold, 80 Ct', 1809, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2737, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (31, 'Crab - Claws, 26 - 30', 9848, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 3868, 61);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (32, 'Oats Large Flake', 12511, '', 3528, 41);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (33, 'Bread - Italian Sesame Poly', 2005, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1808, 100);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (34, 'Wine - Cotes Du Rhone Parallele', 12379, '', 4101, 8);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (35, 'Quail - Whole, Boneless', 11338, '', 4701, 30);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (36, 'Beef - Striploin Aa', 17219, '', 2455, 91);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (37, 'External Supplier', 9592, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 2236, 26);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (38, 'Muffin Mix - Blueberry', 16170, '', 3611, 27);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (39, 'Salt - Rock, Course', 17068, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 2018, 79);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (40, 'Pur Source', 18015, '', 2468, 43);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (41, 'Mustard - Individual Pkg', 10883, '', 3531, 97);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (42, 'Butcher Twine 4r', 13911, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 520, 8);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (43, 'Brocolinni - Gaylan, Chinese', 12073, '', 3559, 39);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (44, 'Ice Cream - Super Sandwich', 11665, '', 3388, 73);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (45, 'Butter - Pod', 13129, '', 4158, 91);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (46, 'Sauce - Sesame Thai Dressing', 17851, '', 2309, 71);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (47, 'Chocolate - Mi - Amere Semi', 8423, '', 1525, 88);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (48, 'Island Oasis - Cappucino Mix', 17724, '', 2576, 35);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (49, 'Quail - Whole, Boneless', 17736, '', 4548, 32);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (50, 'Muffin - Zero Transfat', 18952, '', 3185, 55);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (51, 'Cheese - Havarti, Roasted Garlic', 7779, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 700, 35);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (52, 'Scallops - Live In Shell', 19033, '', 705, 3);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (53, 'Bar Mix - Lime', 5660, '', 4562, 80);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (54, 'Bagel - Sesame Seed Presliced', 18764, '', 4461, 93);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (55, 'Muffin Batt - Choc Chk', 2637, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 4704, 82);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (56, 'Ecolab Silver Fusion', 10409, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 641, 22);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (57, 'Mushroom Morel Fresh', 6837, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 3065, 60);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (58, 'Split Peas - Yellow, Dry', 14965, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 4555, 10);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (59, 'Bread - Multigrain, Loaf', 13658, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 2764, 61);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (60, 'Cocoa Powder - Natural', 1051, '', 1444, 87);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (61, 'Spice - Montreal Steak Spice', 13485, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 4796, 71);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (62, 'Filter - Coffee', 4506, '', 1391, 11);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (63, 'Tofu - Soft', 9802, '', 4931, 80);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (64, 'Pepsi - 600ml', 18275, '', 1656, 53);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (65, 'Sugar - Palm', 18753, '', 4600, 41);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (66, 'Chocolate - Sugar Free Semi Choc', 8984, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 964, 84);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (67, 'Cheese - Romano, Grated', 19702, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 3173, 77);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (68, 'Tea - English Breakfast', 16182, '', 3251, 65);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (69, 'Muffin Mix - Lemon Cranberry', 8436, '', 4536, 100);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (70, 'Dc - Sakura Fu', 433, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 3875, 34);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (71, 'Pastry - Choclate Baked', 17359, '', 4117, 2);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (72, 'Pastry - Lemon Danish - Mini', 263, '', 2320, 27);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (73, 'Spring Roll Veg Mini', 18824, '', 4013, 16);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (74, 'Rice - Sushi', 15585, '', 1793, 42);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (75, 'Water - Perrier', 6906, '', 1844, 70);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (76, 'Straws - Cocktale', 3631, '', 1542, 31);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (77, 'Appetizer - Mango Chevre', 17888, '', 4944, 28);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (78, 'Jolt Cola', 2529, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1880, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (79, 'Raisin - Golden', 11750, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 4649, 80);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (80, 'Flour - Pastry', 15888, '', 1759, 51);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (81, 'Muffin Mix - Lemon Cranberry', 1298, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 3935, 72);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (82, 'Glove - Cutting', 17267, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1617, 67);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (83, 'Cookies - Amaretto', 834, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 3684, 56);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (84, 'Truffle - Whole Black Peeled', 16760, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 4675, 49);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (85, 'Bread - Sticks, Thin, Plain', 8510, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 4645, 28);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (86, 'Coffee - 10oz Cup 92961', 5355, '', 2971, 9);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (87, 'Coconut - Shredded, Unsweet', 15642, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 3360, 40);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (88, 'Flour - Whole Wheat', 10848, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 3245, 36);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (89, 'Soup Campbells - Italian Wedding', 1446, '', 3550, 30);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (90, 'Pepperoni Slices', 5971, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 970, 4);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (91, 'Rice - 7 Grain Blend', 16877, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2714, 88);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (92, 'Mace', 8691, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 1001, 29);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (93, 'Garbage Bags - Clear', 11060, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1326, 18);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (94, 'Bar Nature Valley', 5457, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 3572, 76);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (95, 'Yukon Jack', 15182, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 866, 42);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (96, 'Shrimp - 31/40', 17509, '', 532, 37);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (97, 'Cheese - Brie, Cups 125g', 12830, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 2472, 46);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (98, 'Meldea Green Tea Liquor', 6228, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 3086, 38);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (99, 'Green Scrubbie Pad H.duty', 9164, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 686, 33);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (100, 'Glove - Cutting', 18089, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 868, 7);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (101, 'Chips - Miss Vickies', 16803, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 2262, 64);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (102, 'Cheese - Cheddar, Old White', 6731, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1693, 35);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (103, 'Muffin Batt - Ban Dream Zero', 12192, '', 1621, 30);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (104, 'Pur Source', 3446, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 2486, 37);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (105, 'Wine - Red, Cooking', 285, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1754, 68);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (106, 'Wine - Touraine Azay - Le - Rideau', 219, '', 3622, 1);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (107, 'Bread - Roll, Canadian Dinner', 6327, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 582, 96);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (108, 'Cumin - Whole', 8953, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 3717, 14);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (109, 'Beer - Upper Canada Light', 256, '', 2268, 32);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (110, 'Pants Custom Dry Clean', 11671, '', 2107, 74);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (111, 'Pasta - Fettuccine, Egg, Fresh', 13457, '', 3758, 87);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (112, 'Brandy - Orange, Mc Guiness', 15671, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 3547, 88);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (113, 'Muffin - Mix - Creme Brule 15l', 1574, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 3524, 80);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (114, 'Wine - Red, Harrow Estates, Cab', 11778, '', 4382, 48);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (115, 'Pie Filling - Apple', 7516, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 2352, 93);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (116, 'Wine - Spumante Bambino White', 7758, '', 1624, 34);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (117, 'Peas Snow', 16793, '', 1978, 26);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (118, 'Greens Mustard', 19451, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1765, 19);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (119, 'Bacardi Raspberry', 8285, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1941, 67);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (120, 'Sausage - Liver', 14135, '', 2854, 41);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (121, 'Onion Powder', 5725, '', 3529, 60);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (122, 'Cheese - Comtomme', 315, '', 3316, 6);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (123, 'Turkey Tenderloin Frozen', 1692, 'Fusce consequat. Nulla nisl. Nunc nisl.', 3325, 54);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (124, 'Spice - Greek 1 Step', 11426, '', 1112, 17);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (125, 'Chestnuts - Whole,canned', 2456, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 939, 75);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (126, 'Tuna - Canned, Flaked, Light', 17592, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 3238, 84);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (127, 'Vol Au Vents', 13371, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 2871, 72);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (128, 'Pie Filling - Cherry', 10934, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 3986, 55);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (129, 'Fenngreek Seed', 19500, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 4244, 55);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (130, 'Table Cloth 62x114 Colour', 6905, '', 4765, 1);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (131, 'Arctic Char - Fillets', 3159, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 2549, 97);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (132, 'Rum - Cream, Amarula', 19253, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 708, 42);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (133, 'Glaze - Apricot', 6748, '', 3635, 15);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (134, 'Pork - Inside', 4745, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 3585, 86);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (135, 'Chocolate Bar - Reese Pieces', 15668, '', 1952, 6);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (136, 'Chestnuts - Whole,canned', 3397, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2004, 93);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (137, 'Island Oasis - Pina Colada', 14163, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 2139, 27);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (138, 'Compound - Passion Fruit', 6907, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 4501, 71);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (139, 'Sauce - Salsa', 3414, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 3361, 86);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (140, 'Amaretto', 19293, '', 4505, 16);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (141, 'Rye Special Old', 16987, '', 3120, 51);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (142, 'Cookie - Oatmeal', 1145, '', 1278, 45);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (143, 'Beer - Alexander Kieths, Pale Ale', 7310, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 4287, 67);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (144, 'Olives - Nicoise', 5471, '', 4949, 56);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (145, 'Cucumber - English', 6477, '', 2432, 22);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (146, 'Soup - Knorr, Veg / Beef', 18724, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 932, 3);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (147, 'Vinegar - Raspberry', 4085, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 4920, 48);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (148, 'Lobster - Baby, Boiled', 11400, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 578, 61);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (149, 'Vinegar - White Wine', 2062, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 2140, 83);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (150, 'Tart Shells - Savory, 2', 17245, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1011, 43);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (151, 'Mushroom - Porcini Frozen', 10239, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 4062, 6);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (152, 'Fudge - Chocolate Fudge', 18243, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 4869, 43);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (153, 'Yogurt - Cherry, 175 Gr', 10154, '', 1365, 88);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (154, 'Bread - Focaccia Quarter', 12422, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 4261, 85);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (155, 'Cheese - Perron Cheddar', 16816, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 4250, 45);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (156, 'Wine - White, French Cross', 18666, '', 1206, 28);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (157, 'Vol Au Vents', 9920, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 3595, 2);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (158, 'Cheese - Fontina', 7314, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1952, 91);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (159, 'Chocolate Liqueur - Godet White', 499, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1195, 81);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (160, 'Glass Clear 7 Oz Xl', 4408, '', 4104, 42);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (161, 'Pasta - Tortellini, Fresh', 116, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 4162, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (162, 'Higashimaru Usukuchi Soy', 11352, '', 4327, 38);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (163, 'Pasta - Shells, Medium, Dry', 14127, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 600, 22);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (164, 'Creme De Menth - White', 17434, '', 4177, 2);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (165, 'Oil - Food, Lacquer Spray', 1651, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1322, 94);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (166, 'Shrimp - 150 - 250', 1874, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1641, 24);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (167, 'Hog / Sausage Casing - Pork', 14055, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 2103, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (168, 'Onions - Red', 3524, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1262, 39);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (169, 'Container - Foam Dixie 12 Oz', 13441, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 4846, 2);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (170, 'Lettuce - Lolla Rosa', 232, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 4619, 6);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (171, 'Anchovy Fillets', 11377, '', 1823, 59);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (172, 'Soup Campbells Turkey Veg.', 4092, '', 3739, 20);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (173, 'Veal - Heart', 13778, '', 4629, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (174, 'Plate - Foam, Bread And Butter', 13605, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 4169, 40);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (175, 'Wine - Peller Estates Late', 11563, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 3879, 81);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (176, 'Wine - Bourgogne 2002, La', 10548, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 2685, 95);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (177, 'Phyllo Dough', 11775, '', 3641, 70);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (178, 'Tea - Orange Pekoe', 18244, '', 4489, 8);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (179, 'Salmon - Atlantic, No Skin', 2097, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1146, 82);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (180, 'Fish - Scallops, Cold Smoked', 14907, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 3607, 16);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (181, 'Wine - Cabernet Sauvignon', 15122, '', 1367, 50);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (182, 'Wine - Prosecco Valdobiaddene', 15791, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 4591, 2);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (183, 'Soup - Campbells', 16552, '', 2866, 32);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (184, 'Pepperoni Slices', 19918, '', 3824, 7);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (185, 'Muskox - French Rack', 12790, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1095, 85);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (186, 'Graham Cracker Mix', 15587, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 4991, 62);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (187, 'Carbonated Water - Raspberry', 6478, '', 3097, 57);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (188, 'Anchovy In Oil', 14433, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1447, 49);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (189, 'Kellogs All Bran Bars', 4681, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1608, 49);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (190, 'Juice - Pineapple, 341 Ml', 12652, '', 4824, 65);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (191, 'Cleaner - Comet', 1741, '', 3574, 90);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (192, 'Magnotta - Bel Paese White', 608, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 4007, 7);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (193, 'Juice - Tomato, 48 Oz', 2640, '', 657, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (194, 'Lettuce - Curly Endive', 10535, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1331, 56);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (195, 'Tea - Earl Grey', 9292, '', 2690, 75);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (196, 'Wine - Conde De Valdemar', 19284, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 4095, 68);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (197, 'Wine - Delicato Merlot', 6900, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 2593, 21);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (198, 'Longos - Chicken Cordon Bleu', 13561, '', 4945, 23);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (199, 'Radish', 5736, '', 2842, 7);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (200, 'Soho Lychee Liqueur', 13146, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 2996, 73);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (201, 'Squash - Pepper', 18596, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 3839, 5);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (202, 'Cognac - Courvaisier', 7341, '', 1948, 39);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (203, 'Wine - Red, Mouton Cadet', 9613, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 2740, 69);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (204, 'Oil - Sunflower', 5368, '', 4052, 1);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (205, 'Cheese - Marble', 10130, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 3186, 21);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (206, 'Pork - Ham, Virginia', 9727, '', 1064, 74);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (207, 'Beer - Mcauslan Apricot', 12431, '', 3721, 50);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (208, 'Beer - Sleemans Cream Ale', 13756, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1578, 33);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (209, 'Peach - Fresh', 2688, '', 1732, 79);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (210, 'Vanilla Beans', 16246, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 3115, 57);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (211, 'Rice Pilaf, Dry,package', 16592, '', 720, 67);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (212, 'Squid - Breaded', 16549, '', 937, 21);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (213, 'Carbonated Water - Blackberry', 884, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 684, 43);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (214, 'Pop - Club Soda Can', 237, '', 3813, 66);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (215, 'Pork Salted Bellies', 7403, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 4373, 16);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (216, 'Peach - Halves', 2491, '', 3840, 73);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (217, 'Wine - Casablanca Valley', 6010, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 2308, 73);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (218, 'Pie Filling - Cherry', 294, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1871, 51);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (219, 'Pepper - Julienne, Frozen', 14484, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1368, 74);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (220, 'Longos - Grilled Salmon With Bbq', 4786, '', 2371, 98);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (221, 'Chips - Miss Vickies', 10303, '', 1630, 39);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (222, 'Wine - Lamancha Do Crianza', 8365, '', 1361, 88);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (223, 'Bread - 10 Grain Parisian', 10926, 'Fusce consequat. Nulla nisl. Nunc nisl.', 1136, 42);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (224, 'Ginger - Pickled', 7942, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3531, 45);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (225, 'Schnappes - Peach, Walkers', 18131, '', 3969, 78);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (226, 'Fudge - Cream Fudge', 4947, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 2702, 98);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (227, 'Pasta - Penne, Rigate, Dry', 13498, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 3663, 18);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (228, 'Mushroom - Shitake, Fresh', 12846, '', 1956, 35);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (229, 'Wine - Fat Bastard Merlot', 9050, '', 1452, 95);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (230, 'Sweet Pea Sprouts', 614, '', 3781, 2);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (231, 'Chestnuts - Whole,canned', 9578, '', 3546, 97);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (232, 'Amaretto', 17273, '', 1174, 84);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (233, 'Sour Puss Raspberry', 17422, '', 1912, 40);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (234, 'Quail - Jumbo', 10871, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1870, 9);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (235, 'Beef - Striploin', 790, '', 2044, 74);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (236, 'Artichoke - Hearts, Canned', 9153, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1188, 39);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (237, 'Wine - Piper Heidsieck Brut', 3794, '', 671, 28);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (238, 'Sponge Cake Mix - Chocolate', 942, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1762, 93);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (239, 'Trueblue - Blueberry Cranberry', 18508, '', 569, 58);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (240, 'Flour - Corn, Fine', 13270, '', 3645, 77);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (241, 'Eggs - Extra Large', 19388, '', 3029, 3);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (242, 'Pail For Lid 1537', 6541, '', 4376, 76);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (243, 'Lentils - Green Le Puy', 13437, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1650, 47);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (244, 'Cod - Salted, Boneless', 1693, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 2634, 79);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (245, 'Tea - Orange Pekoe', 5677, 'Fusce consequat. Nulla nisl. Nunc nisl.', 3983, 45);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (246, 'Irish Cream - Baileys', 2165, '', 2049, 24);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (247, 'Steampan Lid', 18315, '', 4691, 56);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (248, 'Rum - Dark, Bacardi, Black', 7078, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1703, 67);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (249, 'Buffalo - Tenderloin', 12420, '', 3718, 43);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (250, 'Mayonnaise - Individual Pkg', 3765, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 890, 68);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (251, 'Soup - Base Broth Beef', 12912, '', 3956, 22);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (252, 'Eggplant - Baby', 19785, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 2252, 55);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (253, 'Wine - Red, Cabernet Merlot', 15203, '', 4733, 43);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (254, 'Jameson Irish Whiskey', 7103, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1822, 14);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (255, 'Wine - Chateau Aqueria Tavel', 9779, '', 4787, 17);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (256, 'Dome Lid Clear P92008h', 16624, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1851, 33);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (257, 'Nut - Macadamia', 10569, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 3553, 4);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (258, 'Beef - Flank Steak', 13001, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 2584, 85);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (259, 'Chocolate Bar - Smarties', 11738, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1195, 95);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (260, 'Veal - Kidney', 11774, '', 4546, 25);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (261, 'Pepper - Cayenne', 5854, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1124, 26);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (262, 'Jam - Marmalade, Orange', 10354, '', 1622, 78);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (263, 'Broom And Broom Rack White', 18419, '', 4134, 94);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (264, 'Ice Cream Bar - Oreo Cone', 10404, '', 3809, 27);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (265, 'Table Cloth 90x90 White', 7427, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 3760, 86);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (266, 'Sage - Rubbed', 18581, 'Fusce consequat. Nulla nisl. Nunc nisl.', 1251, 46);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (267, 'Oil - Peanut', 3488, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 4269, 61);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (268, 'Brandy - Bar', 704, '', 3103, 90);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (269, 'Bread - Bistro Sour', 1009, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 2506, 55);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (270, 'Sauce - Soya, Dark', 17744, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1441, 7);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (271, 'Capon - Breast, Double, Wing On', 18145, '', 3954, 58);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (272, 'Coke - Classic, 355 Ml', 16926, '', 4577, 7);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (273, 'Rye Special Old', 19484, '', 4968, 20);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (274, 'Pork - Bacon, Sliced', 12707, '', 1139, 26);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (275, 'Ecolab Silver Fusion', 14555, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 3154, 100);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (276, 'Shopper Bag - S - 4', 4381, '', 856, 89);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (277, 'Cookie Dough - Chocolate Chip', 1582, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 3730, 59);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (278, 'Wine - Trimbach Pinot Blanc', 14926, '', 3867, 53);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (279, 'Beef - Rouladin, Sliced', 2742, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 2549, 99);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (280, 'Shrimp - Black Tiger 13/15', 18936, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 3574, 24);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (281, 'Asparagus - Frozen', 8591, '', 4671, 17);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (282, 'Salmon - Canned', 13331, '', 1968, 82);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (283, 'Bread - Italian Sesame Poly', 10190, '', 935, 32);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (284, 'Onion - Dried', 14870, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 652, 43);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (285, 'Ecolab Digiclean Mild Fm', 6723, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1972, 75);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (286, 'Melon - Watermelon Yellow', 9327, '', 3269, 40);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (287, 'Rosemary - Dry', 6140, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1240, 91);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (288, 'Sugar - Individual Portions', 6829, '', 1550, 44);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (289, 'Thermometer Digital', 3779, '', 3750, 22);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (290, 'Chocolate - Semi Sweet, Calets', 5509, '', 3711, 47);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (291, 'Cheese - Cheddarsliced', 2059, '', 2586, 5);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (292, 'Wine - Riesling Alsace Ac 2001', 19575, '', 1956, 30);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (293, 'Sprouts - Peppercress', 15795, '', 4986, 41);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (294, 'Wanton Wrap', 1746, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 4871, 35);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (295, 'Butter Ripple - Phillips', 3217, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 2021, 51);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (296, 'Sword Pick Asst', 5579, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 2116, 77);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (297, 'Flour - Teff', 11636, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1068, 68);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (298, 'Pastry - Banana Tea Loaf', 431, '', 1000, 54);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (299, 'Vinegar - White', 1788, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1882, 67);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (300, 'Pie Pecan', 12138, '', 1915, 6);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (301, 'Water Chestnut - Canned', 10282, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 2921, 66);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (302, 'Remy Red', 17218, '', 1242, 2);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (303, 'Brandy - Orange, Mc Guiness', 11376, '', 1947, 31);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (304, 'Salmon - Canned', 12274, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1997, 56);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (305, 'Compound - Raspberry', 16943, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 504, 98);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (306, 'Muffins - Assorted', 5835, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 4115, 3);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (307, 'Water - Evian 355 Ml', 2803, '', 4619, 42);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (308, 'Wine - White, Mosel Gold', 16932, '', 2079, 18);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (309, 'Wine - Rubyport', 6220, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 3566, 32);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (310, 'Pears - Fiorelle', 2024, '', 2536, 90);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (311, 'Glass - Wine, Plastic, Clear 5 Oz', 17263, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 3908, 16);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (312, 'Thyme - Lemon, Fresh', 3104, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 2319, 5);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (313, 'Pork - Suckling Pig', 19660, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1291, 66);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (314, 'Cheese - Cheddar, Mild', 17958, '', 2259, 78);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (315, 'Truffle Cups - Red', 12799, '', 1888, 30);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (316, 'Chips Potato Swt Chilli Sour', 4354, '', 1904, 54);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (317, 'Kiwano', 4353, '', 4307, 19);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (318, 'Ice Cream Bar - Rolo Cone', 2304, '', 2209, 6);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (319, 'Noodles - Cellophane, Thin', 1284, '', 1502, 18);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (320, 'Yoplait Drink', 12661, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 3508, 73);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (321, 'Napkin - Beverage 1 Ply', 1512, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 4068, 63);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (322, 'Hipnotiq Liquor', 4897, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 1610, 93);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (323, 'Veal - Osso Bucco', 3205, '', 1644, 54);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (324, 'Bread - Multigrain', 12645, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 2715, 89);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (325, 'Nestea - Ice Tea, Diet', 17597, '', 4659, 62);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (326, 'Pork - Ground', 656, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 3451, 69);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (327, 'Garbage Bags - Black', 18579, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 3742, 39);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (328, 'Pepsi, 355 Ml', 2905, '', 4432, 10);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (329, 'Appetizer - Southwestern', 10554, '', 3673, 55);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (330, 'Table Cloth 54x72 White', 1374, '', 2496, 11);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (331, 'Cleaner - Comet', 18880, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 4229, 36);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (332, 'Tomatoes - Diced, Canned', 4597, '', 947, 17);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (333, 'Milk - Buttermilk', 6844, '', 607, 49);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (334, 'Stock - Beef, White', 8778, '', 3205, 13);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (335, 'Cheese - Augre Des Champs', 394, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 3222, 82);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (336, 'Trout Rainbow Whole', 16277, '', 1092, 98);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (337, 'Foam Cup 6 Oz', 18565, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 3856, 28);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (338, 'Cake - Miini Cheesecake Cherry', 3957, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1439, 74);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (339, 'Grapefruit - Pink', 19355, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1634, 30);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (340, 'Beer - Sleemans Honey Brown', 12561, '', 1154, 76);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (341, 'Anchovy In Oil', 13537, '', 3667, 24);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (342, 'Wine - Kwv Chenin Blanc South', 15638, '', 4274, 20);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (343, 'Pork - Belly Fresh', 18915, '', 580, 21);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (344, 'Wine - Sauvignon Blanc Oyster', 4938, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 611, 96);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (345, 'Pate - Peppercorn', 17641, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1635, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (346, 'Wine - Red, Cooking', 1408, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 2182, 30);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (347, 'Cheese - Le Cheve Noir', 337, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 2712, 78);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (348, 'Wine - White, Lindemans Bin 95', 6413, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 2335, 16);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (349, 'Wakami Seaweed', 8997, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 607, 43);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (350, 'Sparkling Wine - Rose, Freixenet', 16220, '', 2797, 71);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (351, 'Cookies - Assorted', 1061, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 3743, 72);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (352, 'Pastry - Mini French Pastries', 17500, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1781, 12);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (353, 'Wine - Acient Coast Caberne', 10102, '', 3096, 18);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (354, 'Soup - Base Broth Chix', 5929, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 4616, 30);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (355, 'Muffin Mix - Corn Harvest', 4778, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 3190, 65);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (356, 'Juice - V8, Tomato', 2512, '', 2011, 15);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (357, 'Appetizer - Assorted Box', 10288, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 2902, 76);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (358, 'Grand Marnier', 1025, '', 1032, 7);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (359, 'Olives - Green, Pitted', 15425, '', 4756, 5);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (360, 'Peach - Halves', 19975, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1686, 88);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (361, 'Bread Base - Goodhearth', 12730, '', 4969, 9);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (362, 'Wine - Vouvray Cuvee Domaine', 6243, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 737, 13);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (363, 'Lidsoupcont Rp12dn', 19548, '', 3428, 79);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (364, 'Veal - Inside Round / Top, Lean', 7721, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1825, 20);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (365, 'Thyme - Lemon, Fresh', 17675, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 2204, 50);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (366, 'The Pop Shoppe - Grape', 15323, '', 4561, 27);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (367, 'Potatoes - Instant, Mashed', 2493, '', 1160, 78);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (368, 'Wine - Alicanca Vinho Verde', 9891, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 4953, 47);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (369, 'Oats Large Flake', 2132, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 2349, 9);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (370, 'Numi - Assorted Teas', 5969, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 4613, 2);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (371, 'Food Colouring - Orange', 5374, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 2843, 8);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (372, 'Towel - Roll White', 14717, '', 1391, 72);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (373, 'Ecolab - Balanced Fusion', 9007, '', 3893, 25);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (374, 'Onions - Pearl', 12092, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 768, 54);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (375, 'Chickensplit Half', 15992, '', 1123, 45);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (376, 'The Pop Shoppe - Root Beer', 4112, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1322, 8);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (377, 'Zucchini - Yellow', 10029, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 2085, 63);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (378, 'Pepper - Julienne, Frozen', 4722, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 2424, 76);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (379, 'Wine - Chablis 2003 Champs', 4230, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 3793, 50);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (380, 'Plaintain', 3046, '', 3477, 24);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (381, 'Cabbage - Green', 5260, '', 4860, 32);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (382, 'Wasabi Powder', 16947, '', 4479, 65);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (383, 'Yogurt - Plain', 2298, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1546, 74);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (384, 'Salmon Atl.whole 8 - 10 Lb', 15813, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 553, 29);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (385, 'Garbage Bags - Clear', 14092, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2582, 99);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (386, 'Tequila - Sauza Silver', 14886, '', 3981, 20);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (387, 'Artichoke - Hearts, Canned', 17986, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 4030, 23);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (388, 'Flour - Semolina', 12135, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 2135, 95);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (389, 'Sponge Cake Mix - Chocolate', 17335, '', 611, 46);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (390, 'Boogies', 4326, 'Fusce consequat. Nulla nisl. Nunc nisl.', 4739, 12);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (391, 'Shiratamako - Rice Flour', 6359, '', 1213, 30);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (392, 'Beef - Tenderloin', 10354, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 2814, 96);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (393, 'Apple - Northern Spy', 8849, '', 1785, 47);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (394, 'Swordfish Loin Portions', 4469, '', 1760, 54);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (395, 'Veal - Brisket, Provimi,bnls', 2090, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1570, 97);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (396, 'Wine - Taylors Reserve', 6903, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 4596, 68);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (397, 'Eel Fresh', 17423, '', 3913, 26);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (398, 'Salmon - Atlantic, Skin On', 6948, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1265, 38);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (399, 'Pants Custom Dry Clean', 14938, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 2410, 35);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (400, 'Tortillas - Flour, 8', 7306, '', 1635, 95);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (401, 'Durian Fruit', 2132, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 2586, 81);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (402, 'Cheese - Havarti, Salsa', 10457, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 3147, 71);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (403, 'Marjoram - Dried, Rubbed', 3877, '', 2022, 57);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (404, 'Pork - Chop, Frenched', 6690, '', 685, 46);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (405, 'Flour - Chickpea', 15511, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2486, 16);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (406, 'Soup - Tomato Mush. Florentine', 18956, '', 3026, 23);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (407, 'Cake - Miini Cheesecake Cherry', 10757, '', 1145, 11);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (408, 'Ecolab - Hand Soap Form Antibac', 7928, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 930, 10);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (409, 'Wheat - Soft Kernal Of Wheat', 4449, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 3798, 7);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (410, 'Fish - Atlantic Salmon, Cold', 18312, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 2491, 100);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (411, 'Chicken - Tenderloin', 5242, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3368, 48);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (412, 'Mousse - Mango', 8872, '', 1926, 74);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (413, 'Plastic Arrow Stir Stick', 6636, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 3617, 68);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (414, 'Shrimp - Black Tiger 16/20', 12968, '', 1418, 64);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (415, 'Pasta - Cannelloni, Sheets, Fresh', 1139, '', 4897, 33);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (416, 'Curry Powder', 13056, '', 3504, 77);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (417, 'Wine - Vovray Sec Domaine Huet', 7386, '', 2172, 47);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (418, 'Sloe Gin - Mcguinness', 8620, '', 4915, 61);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (419, 'Split Peas - Green, Dry', 7279, '', 1581, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (420, 'Flower - Leather Leaf Fern', 19798, '', 4548, 89);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (421, 'Chicken - Whole Roasting', 16478, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1459, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (422, 'Shopper Bag - S - 4', 16881, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 2934, 74);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (423, 'Sauce - Thousand Island', 5821, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 3707, 10);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (424, 'Barramundi', 444, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 3451, 72);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (425, 'Salt - Rock, Course', 14414, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 804, 6);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (426, 'Island Oasis - Peach Daiquiri', 17034, '', 1316, 76);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (427, 'Sauce - Hp', 8747, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 2898, 71);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (428, 'Shrimp - Baby, Warm Water', 14737, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 4507, 26);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (429, 'Veal - Brisket, Provimi, Bone - In', 745, '', 831, 77);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (430, 'Basil - Dry, Rubbed', 7709, '', 1556, 88);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (431, 'Salsify, Organic', 4331, '', 1000, 88);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (432, 'Marjoram - Dried, Rubbed', 10723, '', 4631, 23);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (433, 'Pastry - Chocolate Marble Tea', 413, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 4422, 9);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (434, 'Sauce - Balsamic Viniagrette', 8877, '', 4078, 59);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (435, 'Cheese - La Sauvagine', 12498, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1046, 6);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (436, 'Radish - Black, Winter, Organic', 9260, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 3146, 90);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (437, 'Sambuca Cream', 7907, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 4369, 40);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (438, 'Flour - Fast / Rapid', 1170, '', 2185, 37);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (439, 'Cloves - Ground', 10521, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 2838, 46);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (440, 'Wine - Chateau Bonnet', 3533, '', 2460, 8);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (441, 'Lamb - Sausage Casings', 1545, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 932, 39);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (442, 'Curry Powder', 15346, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 4042, 36);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (443, 'Turkey - Breast, Double', 15292, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 4851, 29);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (444, 'Chocolate - Liqueur Cups With Foil', 10644, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 4363, 81);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (445, 'Muffin - Zero Transfat', 3467, '', 994, 36);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (446, 'Chicken - Whole', 6552, '', 4658, 70);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (447, 'Chinese Foods - Chicken', 9981, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 4149, 1);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (448, 'Spinach - Baby', 402, '', 1069, 47);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (449, 'Shrimp - Baby, Warm Water', 15595, '', 1844, 38);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (450, 'Soup V8 Roasted Red Pepper', 19585, '', 725, 29);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (451, 'Tray - 16in Rnd Blk', 10203, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1576, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (452, 'Nantucket Apple Juice', 13775, '', 4764, 44);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (453, 'Cauliflower', 4327, '', 2373, 5);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (454, 'Shrimp - 16/20, Iqf, Shell On', 520, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1874, 28);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (455, 'Mangostein', 17061, '', 3502, 29);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (456, 'Cookie Dough - Peanut Butter', 9372, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 2207, 76);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (457, 'Foam Tray S2', 6372, '', 3922, 43);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (458, 'Breadfruit', 16205, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1406, 26);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (459, 'Grapes - Green', 14095, '', 1563, 81);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (460, 'Squash - Pepper', 16078, '', 4100, 89);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (461, 'Parsley Italian - Fresh', 14914, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 526, 19);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (462, 'Table Cloth 72x144 White', 6578, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 2735, 100);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (463, 'Lid - 16 Oz And 32 Oz', 18527, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 3328, 75);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (464, 'Energy Drink Bawls', 9775, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 2271, 13);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (465, 'Pears - Anjou', 14841, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 970, 27);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (466, 'Grouper - Fresh', 14397, '', 2963, 41);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (467, 'Fiddlehead - Frozen', 18228, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 2404, 51);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (468, 'Shrimp - Black Tiger 16/20', 8601, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 3616, 43);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (469, 'Muffins - Assorted', 13927, '', 1328, 75);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (470, 'Shrimp - 16/20, Iqf, Shell On', 19731, '', 3816, 54);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (471, 'Bread - Frozen Basket Variety', 2491, '', 4636, 67);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (472, 'Yogurt - Banana, 175 Gr', 6314, '', 4495, 77);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (473, 'Beef - Roasted, Cooked', 18445, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 3869, 95);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (474, 'Oneshot Automatic Soap System', 12559, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 4932, 94);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (475, 'Soup Campbells Beef With Veg', 13406, '', 783, 75);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (476, 'Sauce - Soy Low Sodium - 3.87l', 19608, '', 1497, 8);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (477, 'Cake - Night And Day Choclate', 9379, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 2886, 46);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (478, 'Fib N9 - Prague Powder', 14155, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 4635, 68);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (479, 'Glass - Wine, Plastic, Clear 5 Oz', 5522, '', 892, 62);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (480, 'Leeks - Large', 1321, '', 1167, 63);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (481, 'Water, Tap', 10458, '', 4761, 62);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (482, 'Quail - Jumbo Boneless', 9141, '', 1330, 27);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (483, 'Chicken Giblets', 4769, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1645, 38);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (484, 'Tomatoes - Cherry, Yellow', 10007, '', 4931, 63);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (485, 'Guinea Fowl', 6406, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1284, 81);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (486, 'Marjoram - Dried, Rubbed', 694, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1478, 73);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (487, 'Oil - Shortening - All - Purpose', 7616, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1525, 28);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (488, 'Steel Wool S.o.s', 13466, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 4497, 7);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (489, 'Lamb - Leg, Bone In', 3953, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 4897, 19);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (490, 'Muffin Batt - Ban Dream Zero', 19527, '', 543, 28);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (491, 'Lamb - Whole Head Off,nz', 4813, '', 722, 74);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (492, 'Pastry - Cheese Baked Scones', 9113, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 2766, 88);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (493, 'Foam Cup 6 Oz', 4638, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 2298, 75);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (494, 'Sunflower Seed Raw', 14843, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 2370, 65);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (495, 'Wine - Casillero Del Diablo', 3475, '', 3558, 33);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (496, 'Edible Flower - Mixed', 571, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 927, 52);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (497, 'Momiji Oroshi Chili Sauce', 19572, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 4621, 9);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (498, 'Oranges - Navel, 72', 200, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1661, 15);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (499, 'Evaporated Milk - Skim', 16907, '', 2945, 46);
insert into Product (p_id, p_name, p_cost, p_descrip, p_stock, p_cat_id) values (500, 'Wine - Chardonnay South', 6933, '', 1946, 55);
